In [3]:
import numpy as np
import pandas as pd

import plotly.graph_objects as go
import plotly.express as px

In [4]:
district_df = pd.read_csv("district wise centroids.csv")
district_df

                   State           District   Latitude  Longitude
0    Andaman and Nicobar    Andaman Islands  12.382571  92.822911
1    Andaman and Nicobar    Nicobar Islands   7.835291  93.511601
2         Andhra Pradesh           Adilabad  19.284514  78.813212
3         Andhra Pradesh          Anantapur  14.312066  77.460158
4         Andhra Pradesh           Chittoor  13.331093  78.927639
..                   ...                ...        ...        ...
589          West Bengal  North 24 Parganas  22.062388  88.877940
590          West Bengal           Puruliya  23.254192  86.396853
591          West Bengal  South 24 Parganas  21.854428  88.445370
592          West Bengal     Uttar Dinajpur  26.044619  88.235952
593          West Bengal     West Midnapore  22.354897  87.231014

[594 rows x 4 columns]

In [6]:
pd.read_csv("district wise population and centroids.csv")

,State,District,Latitude,Longitude,Population in 2001,Population in 2011
0,Andhra Pradesh,Anantapur,14.312066,77.460158,3640478,4081148
1,Andhra Pradesh,Chittoor,13.331093,78.927639,3745875,4174064
2,Andhra Pradesh,East Godavari,16.782718,82.243207,4901420,5154296
3,Andhra Pradesh,Guntur,15.884926,80.586576,4465144,4887813
4,Andhra Pradesh,Krishna,16.143873,81.148051,4187841,4517398
...,...,...,...,...,...,...
426,West Bengal,Kolkata,22.550581,88.352765,4572876,4496694
427,West Bengal,Maldah,25.080268,88.171917,3290468,3988845
428,West Bengal,Murshidabad,24.259507,88.168169,5866569,7103807
429,West Bengal,Nadia,23.564110,88.582930,4604827,5167600
430,West Bengal,Uttar Dinajpur,26.044619,88.235952,2441794,3007134

In [7]:
pd.read_csv("district wise population for year 2001 and 2011.csv")

,State,District,Population in 2001,Population in 2011
0,Andaman & Nicobar Islands,Nicobar,42068,36842
1,Andaman & Nicobar Islands,North & Middle Andaman,105613,105597
2,Andaman & Nicobar Islands,South Andaman,208471,238142
3,Andhra Pradesh,Anantapur,3640478,4081148
4,Andhra Pradesh,Chittoor,3745875,4174064
...,...,...,...,...
635,West Bengal,Paschim Medinipur,5193411,5913457
636,West Bengal,Purba Medinipur,4417377,5095875
637,West Bengal,Puruliya (Purulia),2536516,2930115
638,West Bengal,South Twenty Four Parganas,6906689,8161961
639,West Bengal,Uttar Dinajpur,2441794,3007134

In [ ]:
pd.read_csv('hlpca-colnames.csv',)

C:\Users\sumit\AppData\Local\Temp\ipykernel_4520\2929670564.py:1: FutureWarning: The 'verbose' keyword in pd.read_csv is deprecated and will be removed in a future version.
  pd.read_csv('hlpca-colnames.csv',verbose=True)

ParserError: Error tokenizing data. C error: Expected 2 fields in line 112, saw 4

In [10]:
pd.read_csv('india_census_housing-hlpca-full.csv')

,State Code,State Name,District Code,District Name,Tehsil Code,Tehsil Name,Town Code/Village code,Ward No,Area Name,Rural/Urban,...,Contition_T_Total,Contition_T_Good,Contition_T_Livable,Contition_T_Dilapidated,Contition_R_Total,Residence_Good,Residence_Livable,Residence_Dilapidated,Residence_cum_other,Residence_cum_Good
0,1,JAMMU & KASHMIR,1,Kupwara,0,Kupwara,0,0,District - Kupwara,Rural,...,100,33.6,58.1,8.3,90.9,32.7,51.0,7.2,9.1,1.0
1,1,JAMMU & KASHMIR,1,Kupwara,0,Kupwara,0,0,District - Kupwara,Total,...,100,34.8,57.3,7.9,91.0,33.8,50.2,6.9,9.0,0.9
2,1,JAMMU & KASHMIR,1,Kupwara,0,Kupwara,0,0,District - Kupwara,Urban,...,100,45.7,49.5,4.8,91.8,45.0,42.2,4.5,8.2,0.7
3,1,JAMMU & KASHMIR,2,Badgam,0,Badgam,0,0,District - Badgam,Rural,...,100,49.7,46.3,3.9,97.2,49.0,44.5,3.7,2.8,0.7
4,1,JAMMU & KASHMIR,2,Badgam,0,Badgam,0,0,District - Badgam,Total,...,100,51.6,44.7,3.8,97.3,50.8,43.0,3.5,2.7,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,35,ANDAMAN & NICOBAR ISLANDS,639,North & Middle Andaman,0,North & Middle Andaman,0,0,District - North & Middle Andaman,Total,...,100,52.6,44.6,2.8,97.5,51.2,43.5,2.8,2.5,1.4
1904,35,ANDAMAN & NICOBAR ISLANDS,639,North & Middle Andaman,0,North & Middle Andaman,0,0,District - North & Middle Andaman,Urban,...,100,37.5,55.9,6.6,95.8,36.3,53.0,6.5,4.2,1.2
1905,35,ANDAMAN & NICOBAR ISLANDS,640,South Andaman,0,South Andaman,0,0,District - South Andaman,Rural,...,100,63.0,33.5,3.5,98.3,62.0,32.8,3.5,1.7,1.0
1906,35,ANDAMAN & NICOBAR ISLANDS,640,South Andaman,0,South Andaman,0,0,District - South Andaman,Total,...,100,71.5,26.4,2.2,98.5,70.6,25.8,2.1,1.5,0.9
1907,35,ANDAMAN & NICOBAR ISLANDS,640,South Andaman,0,South Andaman,0,0,District - South Andaman,Urban,...,100,77.4,21.4,1.2,98.7,76.6,20.9,1.2,1.3,0.8

In [15]:
full_df = pd.read_csv('india-districts-census-2011.csv')
full_df.head()

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629

In [18]:
our_dict = {
  "identification": [
    "State name",
    "District name"
  ],
  "population_and_gender": [
    "Population",
    "Male",
    "Female"
  ],
  "caste_demographics": [
    "SC",
    "ST"
  ],
  "literacy_and_education": [
    "Literate",
    "Male_Literate",
    "Female_Literate",
    "Below_Primary_Education",
    "Primary_Education",
    "Middle_Education",
    "Secondary_Education",
    "Higher_Education",
    "Graduate_Education",
    "Illiterate_Education",
    "Literate_Education"
  ],
  "employment": [
    "Workers",
    "Male_Workers",
    "Female_Workers",
    "Main_Workers",
    "Marginal_Workers",
    "Non_Workers",
    "Cultivator_Workers",
    "Agricultural_Workers",
    "Other_Workers"
  ],
  "religion": [
    "Hindus",
    "Muslims",
    "Christians",
    "Sikhs"
  ],
  "household_infrastructure": [
    "Households",
    "Urban_Households",
    "Rural_Households",
    "Ownership_Owned_Households",
    "Ownership_Rented_Households",
    "Housholds_with_Electric_Lighting",
    "Households_with_Internet",
    "Households_with_Computer",
    "Households_with_Television",
    "Households_with_Car_Jeep_Van",
    "Households_with_Scooter_Motorcycle_Moped",
    "LPG_or_PNG_Households"
  ],
  "sanitation_and_water": [
    "Having_latrine_facility_within_the_premises_Total_Households",
    "Having_bathing_facility_Total_Households",
    "Main_source_of_drinking_water_Tapwater_Households",
    "Location_of_drinking_water_source_Within_the_premises_Households"
  ],
  "income": [
    "Power_Parity_Less_than_Rs_45000",
    "Power_Parity_Rs_90000_150000",
    "Power_Parity_Rs_150000_330000",
    "Power_Parity_Above_Rs_545000",
    "Total_Power_Parity"
  ]
}
list(our_dict.values())

[['State name', 'District name'],
 ['Population', 'Male', 'Female'],
 ['SC', 'ST'],
 ['Literate',
  'Male_Literate',
  'Female_Literate',
  'Below_Primary_Education',
  'Primary_Education',
  'Middle_Education',
  'Secondary_Education',
  'Higher_Education',
  'Graduate_Education',
  'Illiterate_Education',
  'Literate_Education'],
 ['Workers',
  'Male_Workers',
  'Female_Workers',
  'Main_Workers',
  'Marginal_Workers',
  'Non_Workers',
  'Cultivator_Workers',
  'Agricultural_Workers',
  'Other_Workers'],
 ['Hindus', 'Muslims', 'Christians', 'Sikhs'],
 ['Households',
  'Urban_Households',
  'Rural_Households',
  'Ownership_Owned_Households',
  'Ownership_Rented_Households',
  'Housholds_with_Electric_Lighting',
  'Households_with_Internet',
  'Households_with_Computer',
  'Households_with_Television',
  'Households_with_Car_Jeep_Van',
  'Households_with_Scooter_Motorcycle_Moped',
  'LPG_or_PNG_Households'],
 ['Having_latrine_facility_within_the_premises_Total_Households',
  'Having_bathing_facility_Total_Households',
  'Main_source_of_drinking_water_Tapwater_Households',
  'Location_of_drinking_water_source_Within_the_premises_Households'],
 ['Power_Parity_Less_than_Rs_45000',
  'Power_Parity_Rs_90000_150000',
  'Power_Parity_Rs_150000_330000',
  'Power_Parity_Above_Rs_545000',
  'Total_Power_Parity']]

In [21]:
extract_coloumns = ['State name', 'District name',
'Population', 'Male', 'Female'
'Literate',
  'Male_Literate',
  'Female_Literate',
  'Below_Primary_Education',
  'Primary_Education',
  'Middle_Education',
  'Secondary_Education',
  'Higher_Education',
  'Graduate_Education',
  'Illiterate_Education',
  'Literate_Education',
 'Workers',
  'Male_Workers',
  'Female_Workers',
  'Main_Workers',
  'Marginal_Workers',
  'Non_Workers',
  'Cultivator_Workers',
  'Agricultural_Workers',
  'Other_Workers',
 'Hindus', 'Muslims', 'Christians', 'Sikhs',
 'Households',
  'Urban_Households',
  'Rural_Households',
  'Ownership_Owned_Households',
  'Ownership_Rented_Households',
  'Housholds_with_Electric_Lighting',
  'Households_with_Internet',
  'Households_with_Computer',
  'Households_with_Television',
  'Households_with_Car_Jeep_Van',
  'Households_with_Scooter_Motorcycle_Moped',
  'LPG_or_PNG_Households',
 'Having_latrine_facility_within_the_premises_Total_Households',
  'Having_bathing_facility_Total_Households',
  'Main_source_of_drinking_water_Tapwater_Households',
  'Location_of_drinking_water_source_Within_the_premises_Households',
 'Power_Parity_Less_than_Rs_45000',
  'Power_Parity_Rs_90000_150000',
  'Power_Parity_Rs_150000_330000',
  'Power_Parity_Above_Rs_545000',
  'Total_Power_Parity',  ]

print(extract_coloumns)

['State name', 'District name', 'Population', 'Male', 'FemaleLiterate', 'Male_Literate', 'Female_Literate', 'Below_Primary_Education', 'Primary_Education', 'Middle_Education', 'Secondary_Education', 'Higher_Education', 'Graduate_Education', 'Illiterate_Education', 'Literate_Education', 'Workers', 'Male_Workers', 'Female_Workers', 'Main_Workers', 'Marginal_Workers', 'Non_Workers', 'Cultivator_Workers', 'Agricultural_Workers', 'Other_Workers', 'Hindus', 'Muslims', 'Christians', 'Sikhs', 'Households', 'Urban_Households', 'Rural_Households', 'Ownership_Owned_Households', 'Ownership_Rented_Households', 'Housholds_with_Electric_Lighting', 'Households_with_Internet', 'Households_with_Computer', 'Households_with_Television', 'Households_with_Car_Jeep_Van', 'Households_with_Scooter_Motorcycle_Moped', 'LPG_or_PNG_Households', 'Having_latrine_facility_within_the_premises_Total_Households', 'Having_bathing_facility_Total_Households', 'Main_source_of_drinking_water_Tapwater_Households', 'Location_of_drinking_water_source_Within_the_premises_Households', 'Power_Parity_Less_than_Rs_45000', 'Power_Parity_Rs_90000_150000', 'Power_Parity_Rs_150000_330000', 'Power_Parity_Above_Rs_545000', 'Total_Power_Parity']

In [25]:
full_df

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,PONDICHERRY,Mahe,41816,19143,22673,36470,16610,19860,144,...,2316,4309,1370,838,2208,576,978,1554,1446,10027
636,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,1063,2408,665,340,1005,246,483,729,341,4890
637,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,15397,9935,0,...,685,1895,212,134,346,70,120,190,84,3151
638,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,685,1895,212,134,346,70,120,190,84,3151
639,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,105794,84472,0,...,1371,3020,649,368,1017,265,497,762,376,5782