In [ ]:
# Tho we make project using 
# vary few libraries which support the geospatial data and ploty is one of them .
# so Indian cenus Data with geospatial indexing
# District wise Centroids  uska latitude and longitude center par ha .

# tho hum district and state ko tho plot kar sakta ha .corrdinate latitude and longitude mil gaya  
# sawal ha information kiya dikaya.
# dataset 2 India cenesus 2011 
# ma kafi information ha dikana ko .

In [ ]:
# so we merge the 2 two dataset and then us dataset ko project ka liya use karega
# jab hum streamlit ka project banaya ga

In [1]:
import numpy as np
import pandas as pd

import plotly.graph_objects as go
import plotly.express as px

In [4]:
latitude_longitude = pd.read_csv("district wise centroids.csv")
latitude_longitude

                   State           District   Latitude  Longitude
0    Andaman and Nicobar    Andaman Islands  12.382571  92.822911
1    Andaman and Nicobar    Nicobar Islands   7.835291  93.511601
2         Andhra Pradesh           Adilabad  19.284514  78.813212
3         Andhra Pradesh          Anantapur  14.312066  77.460158
4         Andhra Pradesh           Chittoor  13.331093  78.927639
..                   ...                ...        ...        ...
589          West Bengal  North 24 Parganas  22.062388  88.877940
590          West Bengal           Puruliya  23.254192  86.396853
591          West Bengal  South 24 Parganas  21.854428  88.445370
592          West Bengal     Uttar Dinajpur  26.044619  88.235952
593          West Bengal     West Midnapore  22.354897  87.231014

[594 rows x 4 columns]

In [5]:
# in 2011 their are 640 district in india but our data have 594 distict so not much data is missing . 
# lets check if their is duplicated data or not
latitude_longitude.isnull().sum()

State        0
District     0
Latitude     0
Longitude    0
dtype: int64

In [16]:
censes = pd.read_csv('india-districts-census-2011.csv')
censes

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,PONDICHERRY,Mahe,41816,19143,22673,36470,16610,19860,144,...,2316,4309,1370,838,2208,576,978,1554,1446,10027
636,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,1063,2408,665,340,1005,246,483,729,341,4890
637,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,15397,9935,0,...,685,1895,212,134,346,70,120,190,84,3151
638,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,685,1895,212,134,346,70,120,190,84,3151
639,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,105794,84472,0,...,1371,3020,649,368,1017,265,497,762,376,5782

In [18]:
censes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Columns: 118 entries, District code to Total_Power_Parity
dtypes: int64(116), object(2)
memory usage: 590.1+ KB

In [ ]:
# so their are 116 numericals coloumns and 2 cateogrical coloumns
# ek district code ko hamna drop kiya ha

In [23]:
censes.columns.to_list()

['District code',
 'State name',
 'District name',
 'Population',
 'Male',
 'Female',
 'Literate',
 'Male_Literate',
 'Female_Literate',
 'SC',
 'Male_SC',
 'Female_SC',
 'ST',
 'Male_ST',
 'Female_ST',
 'Workers',
 'Male_Workers',
 'Female_Workers',
 'Main_Workers',
 'Marginal_Workers',
 'Non_Workers',
 'Cultivator_Workers',
 'Agricultural_Workers',
 'Household_Workers',
 'Other_Workers',
 'Hindus',
 'Muslims',
 'Christians',
 'Sikhs',
 'Buddhists',
 'Jains',
 'Others_Religions',
 'Religion_Not_Stated',
 'LPG_or_PNG_Households',
 'Housholds_with_Electric_Lighting',
 'Households_with_Internet',
 'Households_with_Computer',
 'Rural_Households',
 'Urban_Households',
 'Households',
 'Below_Primary_Education',
 'Primary_Education',
 'Middle_Education',
 'Secondary_Education',
 'Higher_Education',
 'Graduate_Education',
 'Other_Education',
 'Literate_Education',
 'Illiterate_Education',
 'Total_Education',
 'Age_Group_0_29',
 'Age_Group_30_49',
 'Age_Group_50',
 'Age not stated',
 'Households_with_Bicycle',
 'Households_with_Car_Jeep_Van',
 'Households_with_Radio_Transistor',
 'Households_with_Scooter_Motorcycle_Moped',
 'Households_with_Telephone_Mobile_Phone_Landline_only',
 'Households_with_Telephone_Mobile_Phone_Mobile_only',
 'Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car',
 'Households_with_Television',
 'Households_with_Telephone_Mobile_Phone',
 'Households_with_Telephone_Mobile_Phone_Both',
 'Condition_of_occupied_census_houses_Dilapidated_Households',
 'Households_with_separate_kitchen_Cooking_inside_house',
 'Having_bathing_facility_Total_Households',
 'Having_latrine_facility_within_the_premises_Total_Households',
 'Ownership_Owned_Households',
 'Ownership_Rented_Households',
 'Type_of_bathing_facility_Enclosure_without_roof_Households',
 'Type_of_fuel_used_for_cooking_Any_other_Households',
 'Type_of_latrine_facility_Pit_latrine_Households',
 'Type_of_latrine_facility_Other_latrine_Households',
 'Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households',
 'Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households',
 'Not_having_bathing_facility_within_the_premises_Total_Households',
 'Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households',
 'Main_source_of_drinking_water_Un_covered_well_Households',
 'Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households',
 'Main_source_of_drinking_water_Spring_Households',
 'Main_source_of_drinking_water_River_Canal_Households',
 'Main_source_of_drinking_water_Other_sources_Households',
 'Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households',
 'Location_of_drinking_water_source_Near_the_premises_Households',
 'Location_of_drinking_water_source_Within_the_premises_Households',
 'Main_source_of_drinking_water_Tank_Pond_Lake_Households',
 'Main_source_of_drinking_water_Tapwater_Households',
 'Main_source_of_drinking_water_Tubewell_Borehole_Households',
 'Household_size_1_person_Households',
 'Household_size_2_persons_Households',
 'Household_size_1_to_2_persons',
 'Household_size_3_persons_Households',
 'Household_size_3_to_5_persons_Households',
 'Household_size_4_persons_Households',
 'Household_size_5_persons_Households',
 'Household_size_6_8_persons_Households',
 'Household_size_9_persons_and_above_Households',
 'Location_of_drinking_water_source_Away_Households',
 'Married_couples_1_Households',
 'Married_couples_2_Households',
 'Married_couples_3_Households',
 'Married_couples_3_or_more_Households',
 'Married_couples_4_Households',
 'Married_couples_5__Households',
 'Married_couples_None_Households',
 'Power_Parity_Less_than_Rs_45000',
 'Power_Parity_Rs_45000_90000',
 'Power_Parity_Rs_90000_150000',
 'Power_Parity_Rs_45000_150000',
 'Power_Parity_Rs_150000_240000',
 'Power_Parity_Rs_240000_330000',
 'Power_Parity_Rs_150000_330000',
 'Power_Parity_Rs_330000_425000',
 'Power_Parity_Rs_425000_545000',
 'Power_Parity_Rs_330000_545000',
 'Power_Parity_Above_Rs_545000',
 'Total_Power_Parity']

In [24]:
censes_df = censes[['District name', 'Population', 'Male','Female','Literate','Male_Literate', 'Female_Literate','Housholds_with_Electric_Lighting',
'Households_with_Internet','Rural_Households',"Urban_Households",'Total_Power_Parity' ,]]
censes_df

,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,Housholds_with_Electric_Lighting,Households_with_Internet,Rural_Households,Urban_Households,Total_Power_Parity
0,Kupwara,870354,474190,396164,439654,282823,156831,83071,762,158438,23226,1119
1,Badgam,753745,398041,355704,335649,207741,127908,90190,1999,160649,27190,1066
2,Leh(Ladakh),133487,78971,54516,93770,62834,30936,17250,574,36920,17474,242
3,Kargil,140802,77785,63017,86236,56301,29935,15824,235,40370,7774,214
4,Punch,476835,251899,224936,261724,163333,98391,62900,346,132139,15269,629
...,...,...,...,...,...,...,...,...,...,...,...,...
635,Mahe,41816,19143,22673,36470,16610,19860,7150,574,0,12110,10027
636,Karaikal,200222,97809,102413,154916,79903,75013,47880,1868,35618,33715,4890
637,Nicobars,36842,20727,16115,25332,15397,9935,9301,57,15958,0,3151
638,North AND Middle Andaman,105597,54861,50736,78683,43186,35497,18641,388,39091,1094,3151
639,South Andaman,238142,127283,110859,190266,105794,84472,52479,2789,34901,50631,5782

In [29]:
final_df = latitude_longitude.merge(censes_df,left_on='District',right_on='District name').drop(columns='District name')
final_df

,State,District,Latitude,Longitude,Population,Male,Female,Literate,Male_Literate,Female_Literate,Housholds_with_Electric_Lighting,Households_with_Internet,Rural_Households,Urban_Households,Total_Power_Parity
0,Andhra Pradesh,Adilabad,19.284514,78.813212,2741239,1369597,1371642,1483347,856350,626997,566108,5512,597466,220248,4181
1,Andhra Pradesh,Anantapur,14.312066,77.460158,4081148,2064495,2016653,2310960,1338474,972486,897970,8606,902997,341431,5799
2,Andhra Pradesh,Chittoor,13.331093,78.927639,4174064,2090204,2083860,2667878,1484794,1183084,944555,13763,907970,395900,5926
3,Andhra Pradesh,East Godavari,16.782718,82.243207,5154296,2569688,2584608,3288577,1716933,1571644,1297273,22411,1199479,406362,7211
4,Andhra Pradesh,Guntur,15.884926,80.586576,4887813,2440521,2447292,2960441,1634726,1325715,1186028,19383,1069877,513113,6981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,3988845,2051541,1937304,2086432,1152019,934413,297716,5357,830318,128678,4191
513,West Bengal,Murshidabad,24.259507,88.168169,7103807,3627564,3476243,4055834,2177187,1878647,541169,7951,1501066,350899,8088
514,West Bengal,Nadia,23.564110,88.582930,5167600,2653768,2513832,3480555,1878866,1601689,623729,12787,1081381,468390,7048
515,West Bengal,Puruliya,23.254192,86.396853,2930115,1496996,1433119,1624905,1002058,622847,189889,3551,653219,99433,3309
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,3007134,1551066,1456068,1489667,853495,636172,199307,2883,683981,94269,3214

In [ ]:
# we are adding two more coloumns literacy rate and sex ratio
final_df['sex_ratio'] = round((final_df['Female']/final_df['Male'])* 100)

In [39]:
final_df['literacy_rate'] = round((final_df['Literate']/final_df['Population']) * 100)

In [40]:
final_df

,State,District,Latitude,Longitude,Population,Male,Female,Literate,Male_Literate,Female_Literate,Housholds_with_Electric_Lighting,Households_with_Internet,Rural_Households,Urban_Households,Total_Power_Parity,sex_ratio,literacy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,2741239,1369597,1371642,1483347,856350,626997,566108,5512,597466,220248,4181,100.0,54.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,4081148,2064495,2016653,2310960,1338474,972486,897970,8606,902997,341431,5799,98.0,57.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,4174064,2090204,2083860,2667878,1484794,1183084,944555,13763,907970,395900,5926,100.0,64.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,5154296,2569688,2584608,3288577,1716933,1571644,1297273,22411,1199479,406362,7211,101.0,64.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,4887813,2440521,2447292,2960441,1634726,1325715,1186028,19383,1069877,513113,6981,100.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,3988845,2051541,1937304,2086432,1152019,934413,297716,5357,830318,128678,4191,94.0,52.0
513,West Bengal,Murshidabad,24.259507,88.168169,7103807,3627564,3476243,4055834,2177187,1878647,541169,7951,1501066,350899,8088,96.0,57.0
514,West Bengal,Nadia,23.564110,88.582930,5167600,2653768,2513832,3480555,1878866,1601689,623729,12787,1081381,468390,7048,95.0,67.0
515,West Bengal,Puruliya,23.254192,86.396853,2930115,1496996,1433119,1624905,1002058,622847,189889,3551,653219,99433,3309,96.0,55.0
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,3007134,1551066,1456068,1489667,853495,636172,199307,2883,683981,94269,3214,94.0,50.0

In [ ]:
# now export our data
#final_df.to_csv('india.csv',index = False)