In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/campusx")

# Query with pandas
df = pd.read_sql("SELECT * FROM USERS", engine)
df

   user_id    name             email password
0        1  manish  manish@gmail.com     1234
1        2   sumit   sumit@yahoo.com     1010
2        3   deepu   deepu@gmail.com     None
3        4  aditya              None     1234
4        5   anand   anand@gmail.com     1234
5        6   ayush   ayush@gmail.com    12345
6        7  piyush  piyush@gmail.com     6789

In [5]:
# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/task_34")

In [4]:
pd.read_csv('country_ab.csv',sep = ';')

             Country  Edition       Region   A   B
0           Abkhazia     2022      Eurasia   5   8
1        Afghanistan     2022         Asia   0   0
2            Albania     2022       Europe   9  12
3            Algeria     2022       Africa   3   4
4            Andorra     2022       Europe  12  15
...              ...      ...          ...  ..  ..
2090       West Bank     2013  Middle East   2   5
2091  Western Sahara     2013       Africa   0   0
2092           Yemen     2013  Middle East   3   4
2093          Zambia     2013       Africa   9  12
2094        Zimbabwe     2013       Africa   3   5

[2095 rows x 5 columns]

In [6]:
df = pd.read_csv('country_ab.csv',sep = ';')

# Write to SQL
df.to_sql(
    name="country_ab",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

2095

In [7]:
df = pd.read_csv('country_cd.csv',sep = ';')

# Write to SQL
df.to_sql(
    name="country_cd",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

2095

In [8]:
df = pd.read_csv('country_cl.csv',sep = ';')

# Write to SQL
df.to_sql(
    name="country_cl",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

2095

In [9]:
df = pd.read_csv('country_efg.csv',sep = ';')

# Write to SQL
df.to_sql(
    name="country_efg",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

2095

In [ ]:
# now transfer the sales database in it

In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/task_34")

In [2]:
pd.read_csv('Customers.csv')

      CustomerID FirstName MiddleInitial   LastName
0              1     Aaron           NaN  Alexander
1              2     Aaron           NaN     Bryant
2              3     Aaron           NaN     Butler
3              4     Aaron           NaN       Chen
4              5     Aaron           NaN    Coleman
...          ...       ...           ...        ...
1995        1996    Autumn             W        Gao
1996        1997    Bailey           NaN      Adams
1997        1998    Bailey           NaN      Baker
1998        1999    Bailey           NaN     Carter
1999        2000    Bailey           NaN    Collins

[2000 rows x 4 columns]

In [3]:
df = pd.read_csv('Customers.csv')

# Write to SQL
df.to_sql(
    name="customers",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

2000

In [4]:
pd.read_csv('Employees.csv')

    EmployeeID    FirstName MiddleInitial        LastName
0            1      Abraham             e          Bennet
1            2     Reginald             l  Blotchet-Halls
2            3       Cheryl             a          Carson
3            4       Michel             e        DeFrance
4            5        Innes             e    del Castillo
5            6          Ann             u            Dull
6            7     Marjorie             r           Green
7            8  Morningstar             r          Greene
8            9         Burt             r      Gringlesby
9           10       Sheryl             u          Hunter
10          11        Livia             a          Karsen
11          12     Charlene             o        Locksley
12          13      Stearns             a      MacFeather
13          14      Heather             c        McBadden
14          15      Michael             '         O'Leary
15          16       Sylvia             a        Panteley
16          17       Albert             i          Ringer
17          18         Anne             i          Ringer
18          19      Meander             m           Smith
19          20         Dean             t        Straight
20          21         Dirk             t        Stringer
21          22      Johnson             h           White
22          23        Akiko             o        Yokomoto

In [5]:
df = pd.read_csv('Employees.csv')

# Write to SQL
df.to_sql(
    name="employees",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

23

In [6]:
pd.read_csv('Products.csv')

     ProductID                   Name   Price
0            1        Adjustable Race    1.60
1            2           Bearing Ball    0.80
2            3        BB Ball Bearing    2.40
3            4  Headset Ball Bearings    0.00
4            5                  Blade  189.60
..         ...                    ...     ...
499        500      ML Bottom Bracket  101.24
500        501      HL Bottom Bracket  121.49
501        502     Road-750 Black, 44  539.99
502        503     Road-750 Black, 48  539.99
503        504     Road-750 Black, 52  539.99

[504 rows x 3 columns]

In [7]:
df = pd.read_csv('Products.csv')

# Write to SQL
df.to_sql(
    name="products",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

504

In [8]:
pd.read_csv('Sales1.csv')

      SalesID  SalesPersonID  CustomerID  ProductID  Quantity
0           1             17       10482        500       500
1           2              5        1964        306       810
2           3              8       12300        123       123
3           4              1        4182        437       437
4           5             14       15723        246       750
...       ...            ...         ...        ...       ...
1995     1996             14       15723        246       750
1996     1997              4       17023        259       763
1997     1998             21       18723        276       780
1998     1999             15         664        293       797
1999     2000              5        1964        306       810

[2000 rows x 5 columns]

In [9]:
df = pd.read_csv('Sales1.csv')

# Write to SQL
df.to_sql(
    name="sales",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

2000

In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/campusx")

In [3]:
df = pd.read_csv(r'C:\Users\sumit\My_code_files\Data Science codes\week 15-SQL Continued\flight project\flights.csv')
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Price
0,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,11:40,785,1 stop,26890
1,SpiceJet,2019-01-03,Banglore,New Delhi,BLR → HYD → DEL,15:35,485,1 stop,7744
2,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,8:00,740,1 stop,27992
3,Air India,2019-01-03,Banglore,New Delhi,BLR → BOM → AMD → DEL,8:50,2345,2 stops,17135
4,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,11:40,1425,1 stop,25735
...,...,...,...,...,...,...,...,...,...
10678,Multiple carriers,2019-12-06,Delhi,Cochin,DEL → BOM → COK,9:15,585,1 stop,11622
10679,IndiGo,2019-12-06,Kolkata,Banglore,CCU → MAA → BLR,8:10,290,1 stop,5069
10680,Jet Airways,2019-12-06,Delhi,Cochin,DEL → BOM → COK,22:50,1210,1 stop,14714
10681,Air Asia,2019-12-06,Kolkata,Banglore,CCU → DEL → BLR,7:35,955,1 stop,5192
10682,Jet Airways,2019-12-06,Delhi,Cochin,DEL → BOM → COK,21:50,395,1 stop,10262

In [4]:
df = pd.read_csv(r'C:\Users\sumit\My_code_files\Data Science codes\week 15-SQL Continued\flight project\flights.csv')


# Write to SQL
df.to_sql(
    name="flights",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

10683

In [2]:
import pandas as pd
from sqlalchemy import create_engine

# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/pratice")

In [3]:
pd.read_csv('athlete_events.csv')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [ ]:
df = pd.read_csv('athlete_events.csv')
# Write to SQL
df.to_sql(
    name="olympics",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

271116

In [5]:
pd.read_csv('noc_regions.csv')

     NOC       region                 notes
0    AFG  Afghanistan                   NaN
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania                   NaN
3    ALG      Algeria                   NaN
4    AND      Andorra                   NaN
..   ...          ...                   ...
225  YEM        Yemen                   NaN
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia                   NaN
229  ZIM     Zimbabwe                   NaN

[230 rows x 3 columns]

In [ ]:
df = pd.read_csv('noc_regions.csv')
# Write to SQL
df.to_sql(
    name="country",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

230

In [1]:
file = r'C:\Users\sumit\My_code_files\Data Science codes\week 07-advanced pandas\ipl_deliveries.csv'
import pandas as pd
pd.read_csv(file).head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [3]:
import pandas as pd
from sqlalchemy import create_engine

# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/campusx")

# Query with pandas
df = pd.read_sql("SELECT * FROM USERS", engine)
df

   user_id    name             email password
0        1  manish  manish@gmail.com     1234
1        2   sumit   sumit@yahoo.com     1010
2        3   deepu   deepu@gmail.com     None
3        4  aditya              None     1234
4        5   anand   anand@gmail.com     1234
5        6   ayush   ayush@gmail.com    12345
6        7  piyush  piyush@gmail.com     6789

In [6]:
ipl_file = r'C:\Users\sumit\My_code_files\Data Science codes\week 07-advanced pandas\deliveries.csv'
df = pd.read_csv(ipl_file)
df

,(match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [7]:
ipl_file = r'C:\Users\sumit\My_code_files\Data Science codes\week 07-advanced pandas\deliveries.csv'
df = pd.read_csv(ipl_file)
# Write to SQL
df.to_sql(
    name="ipl",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

179078