## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [49]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [50]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:
# groupby karo age col nikalo mean apply 
titanic_df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [ ]:
#titanic_df.groupby('Pclass')['Age']
titanic_df['Age'].isna().sum() # so ya par 177 missing values ha 
#vo kon kon sa group ma

177

In [ ]:
# null values nikal la liya total - value = missing value
# count null value ko include nahi karta
# aor size una count karta ha

In [ ]:
# total = missing + non-missing values

In [ ]:
# total values - non missing value = missing values 
mising_values = titanic_df.groupby('Pclass')['Age'].size() - titanic_df.groupby('Pclass')['Age'].count()
# tho har ek group ma null values aa gyi 
mising_values.sum() # -> 177 we are correct 
mising_values

Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [ ]:
titanic_df.groupby('Pclass')['Embarked'].size() - titanic_df.groupby('Pclass')['Embarked'].count()

Pclass
1    2
2    0
3    0
Name: Embarked, dtype: int64

In [ ]:
titanic_df['Embarked'].fillna(titanic_df['Embarked'].mode())
titanic_df.groupby('Pclass')['Embarked'].size() - titanic_df.groupby('Pclass')['Embarked'].count()

Pclass
1    2
2    0
3    0
Name: Embarked, dtype: int64

In [ ]:
titanic_df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [60]:
temp_df = titanic_df.groupby(by=['Embarked','Pclass'])['Fare'].mean().reset_index()
temp_df['Fare']= round(temp_df['Fare'])
temp_df

  Embarked  Pclass   Fare
0        C       1  105.0
1        C       2   25.0
2        C       3   11.0
3        Q       1   90.0
4        Q       2   12.0
5        Q       3   11.0
6        S       1   70.0
7        S       2   20.0
8        S       3   15.0

In [ ]:
temp_df.to_dict()

{'Embarked': {0: 'C',
  1: 'C',
  2: 'C',
  3: 'Q',
  4: 'Q',
  5: 'Q',
  6: 'S',
  7: 'S',
  8: 'S'},
 'Pclass': {0: 1, 1: 2, 2: 3, 3: 1, 4: 2, 5: 3, 6: 1, 7: 2, 8: 3},
 'Fare': {0: 105.0,
  1: 25.0,
  2: 11.0,
  3: 90.0,
  4: 12.0,
  5: 11.0,
  6: 70.0,
  7: 20.0,
  8: 15.0}}

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [61]:
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
fifa_df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,516,419,24,3,5,28,4,0

In [ ]:
def z_normalisation(group_col:pd.DataFrame,coloumn:pd.Series)->pd.DataFrame:
    group = fifa_df.groupby(group_col)
    
    group['z_normalised score'] = ( group - group[coloumn].mean())/group[coloumn].std()
    return group.apply()
z_normalisation(group_col='Team',coloumn='Passes')

In [ ]:
def z_normal(group):
    group['z_normal '] = ( group - group[coloumn].mean())/group[coloumn].std()
    return group

In [ ]:
cols_to_perform = ['Passes', 'Passes Completed', 'Attempted Line Breaks','Completed Line Breaks']
# this are my coloums to perform z-normlisation 
# perform groupby on team
fifa_df[cols_to_perform]
groups = fifa_df.groupby('Team')
# now make our z_normlisation function 
def z_normalisation(group:pd.DataFrame,coloumns_to_perform:pd.Series) -> pd.DataFrame:
    for coloumn in coloumns_to_perform:
        std = group[coloumn].std()
        mean = group[coloumn].mean()
        group[f'{coloumn}_z_norm'] = (group[coloumn] - mean)/std
        return group

groups.apply(z_normalisation,coloumns_to_perform=cols_to_perform)

C:\Users\sumit\AppData\Local\Temp\ipykernel_12848\1798202604.py:14: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  groups.apply(z_normalisation,coloumns_to_perform=cols_to_perform)

               Sl. No  Match No.       Team        Against Group  Goal  \
Team
Argentina 8         9          5  Argentina   Saudi Arabia     C     1
          46       47         24  Argentina         Mexico     C     2
          77       78         39  Argentina         Poland     C     2
          98       99         50  Argentina      Australia     C     2
          115     116         58  Argentina    Netherlands     C     2
...               ...        ...        ...            ...   ...   ...
Uruguay   63       64         32    Uruguay       Portugal     H     0
          89       90         45    Uruguay          Ghana     H     2
Wales     7         8          4      Wales  United States     B     1
          32       33         17      Wales           Iran     B     0
          68       69         35      Wales        England     B     0

               Possession (%)  Inside Penalty Area  Outside Penalty Area  \
Team
Argentina 8                51                    1                     0
          46               50                    1                     1
          77               67                    1                     1
          98               53                    2                     0
          115              44                    2                     0
...                       ...                  ...                   ...
Uruguay   63               35                    0                     0
          89               39                    2                     0
Wales     7                39                    1                     0
          32               51                    0                     0
          68               33                    0                     0

               Assists  ...  Offsides  Passes  Passes Completed  Crosses  \
Team                    ...
Argentina 8          0  ...        10     593               525       36
          46         2  ...         2     533               464       14
          77         2  ...         0     862               814       22
          98         1  ...         4     711               635        6
          115        1  ...         2     603               511       16
...                ...  ...       ...     ...               ...      ...
Uruguay   63         0  ...         0     390               306       18
          89         1  ...         2     446               361       15
Wales     7          0  ...         1     409               321       15
          32         0  ...         2     508               413       20
          68         0  ...         1     325               261        4

               Crosses Completed  Corners  Free Kicks  Penalties Scored  Pts  \
Team
Argentina 8                   15        9          21                 1    0
          46                   2        4          23                 0    3
          77                   5        9           5                 0    3
          98                   1        1          15                 0    3
          115                  4        8          30                 5    3
...                          ...      ...         ...               ...  ...
Uruguay   63                   5        2          13                 0    0
          89                   4        2          20                 0    3
Wales     7                    6        3          15                 1    1
          32                   5        2          12                 0    1
          68                   1        1          10                 0    0

               Passes_z_norm
Team
Argentina 8        -0.208138
          46       -0.630447
          77        1.685214
          98        0.622403
          115      -0.137753
...                      ...
Uruguay   63       -0.931702
          89       -0.124867
Wales     7        -0.054584
          32        1.026174
          68       -0.971590

[128 rows x 39 columns]

In [ ]:
# groupby karo aor multiindex use karka multiple  aggreate option lagao
fifa_df.groupby('Team').agg({
    'Passes':['min','max'],
    'Yellow Cards':['min','max','mean'],
    'Attempted Line Breaks':['min','max','std']
})

               Passes       Yellow Cards               Attempted Line Breaks  \
                  min   max          min max      mean                   min
Team
Argentina         408   862            0   8  2.285714                   141
Australia         286   466            0   3  1.750000                   133
Belgium           512   685            1   3  1.666667                   167
Brazil            548   695            0   3  1.200000                   164
Cameroon          295   500            1   5  2.666667                   144
Canada            448   536            2   4  2.666667                   102
Costa Rica        231   454            1   3  2.000000                    86
Croatia           461   724            0   2  1.142857                    97
Denmark           537   650            1   2  1.666667                   173
Ecuador           429   484            0   2  1.000000                   143
England           508   810            0   1  0.200000                   133
France            358   734            0   3  1.142857                   126
Germany           352   827            0   3  1.000000                   143
Ghana             319   460            2   4  2.666667                   122
Iran              232   463            2   3  2.333333                    56
Japan             225   591            0   3  1.500000                   104
Korea Republic    359   548            1   2  1.500000                   139
Mexico            356   500            1   4  2.333333                   127
Morocco           229   583            0   3  1.285714                   128
Netherlands       403   786            0   4  1.800000                   168
Poland            303   466            1   3  1.750000                    79
Portugal          461   678            0   3  1.200000                   165
Qatar             424   457            0   4  2.333333                   159
Saudi Arabia      267   560            2   6  4.666667                   147
Senegal           277   511            1   3  1.750000                   143
Serbia            403   513            2   7  4.000000                   140
Spain             647  1070            0   1  0.500000                   186
Switzerland       403   512            1   4  2.250000                   157
Tunisia           328   501            1   3  1.666667                   153
United States     427   572            0   4  1.250000                   143
Uruguay           390   528            1   3  2.000000                   146
Wales             325   508            1   2  1.666667                   104


                max        std
Team
Argentina       249  38.774685
Australia       171  17.682383
Belgium         195  14.422205
Brazil          193  10.691118
Cameroon        182  19.857828
Canada          176  37.753587
Costa Rica      154  38.974351
Croatia         259  54.499891
Denmark         241  34.000000
Ecuador         177  17.009801
England         208  29.676590
France          179  21.407609
Germany         256  56.624494
Ghana           188  33.020196
Iran            195  77.526340
Japan           253  64.048810
Korea Republic  201  27.072434
Mexico          198  40.706265
Morocco         157  10.641339
Netherlands     198  12.759310
Poland          156  36.326070
Portugal        197  13.049904
Qatar           174   7.767453
Saudi Arabia    205  29.022979
Senegal         184  16.938615
Serbia          184  22.188586
Spain           237  24.289916
Switzerland     178   9.032349
Tunisia         200  24.419937
United States   204  27.693260
Uruguay         186  22.030282
Wales           208  53.028294

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [ ]:
import pandas as pd
ipl = pd.read_csv('ipl_deliveries.csv')
# chasing matlab innings apki 2nd honi chaya use boolean indexing 
ipl['innings'] == 2
# highest score batao 
ipl[ipl['innings'] == 2]

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
120,1312200,Rajasthan RoyalsGujarat Titans,2,0,1,WP Saha,TA Boult,Shubman Gill,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
121,1312200,Rajasthan RoyalsGujarat Titans,2,0,2,WP Saha,TA Boult,Shubman Gill,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
122,1312200,Rajasthan RoyalsGujarat Titans,2,0,3,WP Saha,TA Boult,Shubman Gill,NaN,1,0,1,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
123,1312200,Rajasthan RoyalsGujarat Titans,2,0,4,Shubman Gill,TA Boult,WP Saha,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
124,1312200,Rajasthan RoyalsGujarat Titans,2,0,5,Shubman Gill,TA Boult,WP Saha,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

In [ ]:

ipl = pd.read_csv('ipl_deliveries.csv')

def highest_score(batsman):
    # batsman name and inning 2 honi chya 
    temp_df = ipl[(ipl['batter'] == batsman) & (ipl['innings'] == 2)]
    # groubby id par batsman ka run ka and than sort value 
    return temp_df.groupby('ID')['batsman_run'].sum().sort_values(ascending=False).values[0]
highest_score(batsman='V Kohli')

108

strike rate statistics used to measure the performance of the player 
for batter and bowler different represent the average run scored per 100 balls
    
$strike-rate = \frac{total-runs-scored}{total-balls-faced }$

In [ ]:
def strike_rat(player_name:str)-> int:
    pass

In [32]:
# so first calucate total_balls_faced -> count
# and then calculate total_run_scored -> sum

batter_df = ipl.groupby(by=['batter','innings']).agg({'batsman_run':'sum','ballnumber': 'count'}).reset_index()
batter_df['strike_rate'] = round(batter_df['batsman_run']/batter_df['ballnumber'],1)
batter_df['innings'] == 2
batter_df[(batter_df['innings'] == 2) & (batter_df['ballnumber'] > 100)]

               batter  innings  batsman_run  ballnumber  strike_rate
17           A Mishra        2          217         234          0.9
29          A Symonds        2          352         309          1.1
49     AB de Villiers        2         1999        1482          1.3
55       AC Gilchrist        2         1126         792          1.4
65         AD Mathews        2          314         274          1.1
...               ...      ...          ...         ...          ...
1122  Y Venugopal Rao        2          464         389          1.2
1125      YBK Jaiswal        2          259         184          1.4
1127        YK Pathan        2         1879        1293          1.5
1132      YV Takawale        2          130         122          1.1
1138     Yuvraj Singh        2         1240        1074          1.2

[184 rows x 5 columns]

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

in cricket, "dismissed" means that the batsman has lost their wicket.
"A bowler has dismissed a batsman X times," it means that the bowler has taken the wicket of that batsman X times in different matches or innings.

In [73]:
ipl.columns

Index(['ID', 'Team', 'innings', 'overs', 'ballnumber', 'batter', 'bowler',
       'non-striker', 'extra_type', 'batsman_run', 'extras_run', 'total_run',
       'non_boundary', 'isWicketDelivery', 'player_out', 'kind',
       'fielders_involved', 'BattingTeam', 'BowlingTeam'],
      dtype='object')

In [ ]:
# so muja nikalan ha batsman bowler pair jisma bowler na wicket max li ho and runner minimium ho 
pair_df = ipl.groupby(by=['batter','bowler']).agg({'isWicketDelivery': 'count','batsman_run': 'sum'}).reset_index()
# ab hum chata ha wicket max (descending) sort ho and batsman_run min(ascending) ho 
pair_df.sort_values(by=['isWicketDelivery','batsman_run'],ascending=[False,True])

              batter           bowler  isWicketDelivery  batsman_run
22745        V Kohli        RA Jadeja               134          140
22736        V Kohli         R Ashwin               131          160
17274      RG Sharma        SP Narine               128          137
19536       SK Raina  Harbhajan Singh               125          132
18403       S Dhawan  Harbhajan Singh               123          147
...              ...              ...               ...          ...
16304       R Powell          SS Iyer                 1            6
16513  R Vinay Kumar     DE Bollinger                 1            6
17256      RG Sharma         S Narwal                 1            6
17513       RP Singh        JA Morkel                 1            6
18129    Rashid Khan   Sandeep Sharma                 1            6

[24213 rows x 4 columns]

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [42]:
# ya bhi same Question ha upar wala jasa
# bas run max(descending) and wicket min(asecending ho )
# so muja nikalan ha batsman bowler pair jisma bowler na wicket max li ho and runner minimium ho 
pair_df = ipl.groupby(by=['batter','bowler']).agg({'isWicketDelivery': 'count','batsman_run': 'sum'}).reset_index()
# ab hum chata h
pair_df.sort_values(by=['isWicketDelivery','batsman_run'],ascending=[True,False])

             batter           bowler  isWicketDelivery  batsman_run
2542     Avesh Khan        YS Chahal                 1            6
3785       CH Gayle        TK Curran                 1            6
4358      DA Miller         CH Gayle                 1            6
5639        DR Sams           KR Sen                 1            6
5839   DT Christian  C de Grandhomme                 1            6
...             ...              ...               ...          ...
18403      S Dhawan  Harbhajan Singh               123          147
19536      SK Raina  Harbhajan Singh               125          132
17274     RG Sharma        SP Narine               128          137
22736       V Kohli         R Ashwin               131          160
22745       V Kohli        RA Jadeja               134          140

[24213 rows x 4 columns]

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [ ]:
#In cricket, the non-striker is the batsman who is at the bowler's end (not facing the current delivery).

In [ ]:
ipl[]

In [48]:
# two battsman hota ha na unka group banyo 
# fir run par max(desc) and ball par count lagao
# fir strike rate calucate karo 
batting_pair_df = ipl.groupby(by=['batter','non-striker']).agg({'batsman_run':'sum','ballnumber': 'count'}).reset_index()
batting_pair_df.sort_values(by=['batsman_run','ballnumber'],ascending=[False,True])

              batter      non-striker  batsman_run  ballnumber
292   AB de Villiers          V Kohli         1566        1031
1283        CH Gayle          V Kohli         1508        1006
7493         V Kohli   AB de Villiers         1474        1028
1579       DA Warner         S Dhawan         1354         935
7502         V Kohli         CH Gayle         1142         967
...              ...              ...          ...         ...
1954     DS Kulkarni         MA Khote            0           9
1774       DJ Jacobs          RE Levi            0          10
4675        N Pooran  Abhishek Sharma            0          10
5877        RP Singh          PP Ojha            0          11
4733        ND Doshi          SW Tait            0          13

[8062 rows x 4 columns]