In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/zomato")

In [2]:
pd.read_csv('users.csv')

   user_id      name               email password
0        1    Nitish    nitish@gmail.com    p252h
1        2  Khushboo  khushboo@gmail.com    hxn9b
2        3   Vartika   vartika@gmail.com    9hu7j
3        4     Ankit     ankit@gmail.com    lkko3
4        5      Neha      neha@gmail.com    3i7qm
5        6   Anupama   anupama@gmail.com   46rdw2
6        7   Rishabh   rishabh@gmail.com   4sw123

In [3]:
df = pd.read_csv('users.csv')

# Write to SQL
df.to_sql(
    name="users",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

7

In [4]:
pd.read_csv('restaurants.csv')

   r_id      r_name       cuisine
0     1     dominos       Italian
1     2         kfc      American
2     3        box8  North Indian
3     4  Dosa Plaza  South Indian
4     5  China Town       Chinese

In [5]:
df = pd.read_csv('restaurants.csv')

# Write to SQL
df.to_sql(
    name="restaurants",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

5

In [6]:
pd.read_csv('food.csv')

    f_id            f_name     type
0      1     Non-veg Pizza  Non-veg
1      2         Veg Pizza      Veg
2      3   Choco Lava cake      Veg
3      4     Chicken Wings  Non-veg
4      5   Chicken Popcorn  Non-veg
5      6         Rice Meal      Veg
6      7         Roti meal      Veg
7      8       Masala Dosa      Veg
8      9         Rava Idli      Veg
9     10  Schezwan Noodles      Veg
10    11    Veg Manchurian      Veg

In [7]:
df = pd.read_csv('food.csv')

# Write to SQL
df.to_sql(
    name="food",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

11

In [8]:
pd.read_csv('menu.csv')

    menu_id  r_id  f_id  price
0         1     1     1    450
1         2     1     2    400
2         3     1     3    100
3         4     2     3    115
4         5     2     4    230
5         6     2     5    300
6         7     3     3     80
7         8     3     6    160
8         9     3     7    140
9        10     4     6    230
10       11     4     8    180
11       12     4     9    120
12       13     5     6    250
13       14     5    10    220
14       15     5    11    180

In [9]:
df = pd.read_csv('menu.csv')

# Write to SQL
df.to_sql(
    name="menu",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

15

In [10]:
pd.read_csv('orders.csv')

,order_id,user_id,r_id,amount,date,partner_id,delivery_time,delivery_rating,restaurant_rating
0,1001,1,1,550,2022-05-10,1,25,5,3.0
1,1002,1,2,415,2022-05-26,1,19,5,2.0
2,1003,1,3,240,2022-06-15,5,29,4,NaN
3,1004,1,3,240,2022-06-29,4,42,3,5.0
4,1005,1,3,220,2022-07-10,1,58,1,4.0
5,1006,2,1,950,2022-06-10,2,16,5,NaN
6,1007,2,2,530,2022-06-23,3,60,1,5.0
7,1008,2,3,240,2022-07-07,5,33,4,5.0
8,1009,2,4,300,2022-07-17,4,41,1,NaN
9,1010,2,5,650,2022-07-31,1,67,1,4.0
10,1011,3,1,450,2022-05-10,2,25,3,1.0
11,1012,3,4,180,2022-05-20,5,33,4,1.0
12,1013,3,2,230,2022-05-30,4,45,3,NaN
13,1014,3,2,230,2022-06-11,2,55,1,2.0
14,1015,3,2,230,2022-06-22,3,21,5,NaN
15,1016,4,4,300,2022-05-15,3,31,5,5.0
16,1017,4,4,300,2022-05-30,1,50,1,NaN
17,1018,4,4,400,2022-06-15,2,40,3,5.0
18,1019,4,5,400,2022-06-30,1,70,2,4.0
19,1020,4,5,400,2022-07-15,3,26,5,3.0
20,1021,5,1,550,2022-07-01,5,22,2,NaN
21,1022,5,1,550,2022-07-08,1,34,5,1.0
22,1023,5,2,645,2022-07-15,4,38,5,1.0
23,1024,5,2,645,2022-07-21,2,58,2,1.0
24,1025,5,2,645,2022-07-28,2,44,4,NaN

In [11]:
df = pd.read_csv('orders.csv')

# Write to SQL
df.to_sql(
    name="orders",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

25

In [12]:
pd.read_csv('delivery_partner.csv')

   partner_id partner_name
0           1       Suresh
1           2         Amit
2           3       Lokesh
3           4       Kartik
4           5     Gyandeep

In [13]:
df = pd.read_csv('delivery_partner.csv')

# Write to SQL
df.to_sql(
    name="delivery_partner",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

5

In [14]:
pd.read_csv('order_details.csv')

    id  order_id  f_id
0    1      1001     1
1    2      1001     3
2    3      1002     4
3    4      1002     3
4    5      1003     6
5    6      1003     3
6    7      1004     6
7    8      1004     3
8    9      1005     7
9   10      1005     3
10  11      1006     1
11  12      1006     2
12  13      1006     3
13  14      1007     4
14  15      1007     3
15  16      1008     6
16  17      1008     3
17  18      1009     8
18  19      1009     9
19  20      1010    10
20  21      1010    11
21  22      1010     6
22  23      1011     1
23  24      1012     8
24  25      1013     4
25  26      1014     4
26  27      1015     4
27  28      1016     8
28  29      1016     9
29  30      1017     8
30  31      1017     9
31  32      1018    10
32  33      1018    11
33  34      1019    10
34  35      1019    11
35  36      1020    10
36  37      1020    11
37  38      1021     1
38  39      1021     3
39  40      1022     1
40  41      1022     3
41  42      1023     3
42  43      1023     4
43  44      1023     5
44  45      1024     3
45  46      1024     4
46  47      1024     5
47  48      1025     3
48  49      1025     4
49  50      1025     5

In [16]:
df = pd.read_csv('order_details.csv')

# Write to SQL
df.to_sql(
    name="order_details",         # table name in MySQL
    con=engine,
    if_exists="replace",  
    index=False           
)

50

In [17]:
print(
    'hello world '
)

hello world

In [ ]:
print('start journey')