linear regression ma two technqiues hoti ha ols and gradient descent
ols we study this week and gradient descent on next week

yadi aap simple linear regression padta ho tho multiple linear regression padna asan ho jata ha

 simple linear regression : one cause -> one effect
multiple linear regression : many cause -> one effect

Recap           
simple linear regression : one input (x) one output (y)     
multiple linear regression : multiple input (x1,x2,...xn) and one output

example 
experience (x) salary (y) sa simple linear regression model

aap usko graph ma plot karta ho  agar ya sort of linear ho jesa jesa salry badti ha vasa experience badta ha 
aap ek line draw karta ho aor ya line sabi points sa pass hokar gujarti ha 
fir aap us line ki equation likata ho            
$y = mx + b$        
apka basically m or b ka value chaya hota ha        
now aap kisi ka bhi x (experience) provide karta ho then uska correspoinding apko y (salary) calcuate kar ke deta ha

humna kal ki video ma yahi sika ki m and b kesa nikal sakta ha aor humna pura mathematical formulation draw kiya

## what is multiple linear regresssion

real life ma jab apka paas data hota ha tho tho usma 1 input column nahi hota jesa experieence | salary .
hamara pass ek sa jada predicator hoti ha 
ek sa jada 
city| age| gender | education  | salary

we study
- what is MLR
-  python code
- mathematical formulation
- code from scratch
- problem with OLS solution

example         
| cgpa | iq |  package | 
|----------|----------|----------|
| 7.1 | 80|  8
| 6.89 |90 |9
| ... |...|...|

aesa hamra pass 1000 students ka data ha

```mermaid
flowchart LR
  node_1["cgpa"]
  node_2['iq']
  node_3["model"]
  node_4["placement"]
  node_1 --> node_3
  node_2 --> node_3
  node_3 --> node_4
```

```mermaid
flowchart LR
  node_1["cgpa"]
  node_2['iq']
  node_3["model"]
  node_4["placement"]
  node_1 --inp1--> node_3
  node_2 --inp1--> node_3
  node_3 --1out--> node_4
```

yadi aap simple linear ha hota tho aap line ka equation nikalna ki koshish karta apka data 2d plane ma hota

abhi hamra data 3d space ma tho ab hum plance draw kareaga

ab ya hamra weights bo,b1,,b2,---bn

## python

hum ek 3d data lega

In [ ]:
# import libraries 
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
# create dataset
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [3]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [5]:
df.shape

(100, 3)

In [4]:
df

    feature1  feature2      target
0  -0.445741 -1.997791  -80.896131
1  -1.634687 -0.104104 -110.995651
2  -0.168618  0.944813    5.156919
3   0.473161  1.269235  121.983612
4  -0.700978 -0.673094 -164.370547
..       ...       ...         ...
95  0.299661  0.016166   30.685322
96  1.159020 -0.776302   10.378080
97  0.167966  0.430395   48.998885
98 -0.220599 -1.042850 -151.409168
99 -0.606137 -1.568556  -97.437904

[100 rows x 3 columns]

In [6]:
# 3d plot 
px.scatter_3d(df, x='feature1', y='feature2', z='target')

In [8]:
# do the train test split
from sklearn.model_selection  import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=3)

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
model = LinearRegression()

In [13]:
model.fit(X_train,y_train)

LinearRegression()

In [16]:
y_pred = model.predict(X_test)

In [17]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 46.99329159310292
MSE 3722.3874087428376
R2 score 0.4104686327374655

In [20]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

z_final = model.predict(final).reshape(10,10)

z = z_final

In [21]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

model is trying  to plot a plance jo har paoints sa kam distance sa gajura

In [22]:
model.coef_

array([66.3395235 , 40.95007894])

observe hamra pass ab two coefficient aa raha ha

In [23]:
model.intercept_

-4.936037333733635

what level par humna cheeza clear kar di ab how level par cheeza dekni ha

how level par = hum mathematical formulation karega ki is b0,b1,b2 ...bn ki values kesa calculate kareii

weigths are strength of input and output column

In [ ]:
# import libraries 
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

X,y = load_diabetes(return_X_y=True)

In [ ]:
load_diabetes(as_frame=True)['data']
# deko pahala hi hamra sara columns numerical ha 
# hamara pass 442 patients ka data ha

          age       sex       bmi  ...        s4        s5        s6
0    0.038076  0.050680  0.061696  ... -0.002592  0.019907 -0.017646
1   -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068332 -0.092204
2    0.085299  0.050680  0.044451  ... -0.002592  0.002861 -0.025930
3   -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
4    0.005383 -0.044642 -0.036385  ... -0.002592 -0.031988 -0.046641
..        ...       ...       ...  ...       ...       ...       ...
437  0.041708  0.050680  0.019662  ... -0.002592  0.031193  0.007207
438 -0.005515  0.050680 -0.015906  ...  0.034309 -0.018114  0.044485
439  0.041708  0.050680 -0.015906  ... -0.011080 -0.046883  0.015491
440 -0.045472 -0.044642  0.039062  ...  0.026560  0.044529 -0.025930
441 -0.045472 -0.044642 -0.073030  ... -0.039493 -0.004222  0.003064

[442 rows x 10 columns]

In [2]:
# see the input data (matrix)
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [13]:
# check shape 
X.shape

(442, 10)

In [14]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.])

In [15]:
y.shape

(442,)

## using sklearn

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test , y_train , y_test = train_test_split(X,y ,test_size=0.2,random_state=2)

In [17]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)

In [18]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X=X_train,y=y_train)

LinearRegression()

our equation 
$Y = XB$

In [19]:
y_pred = model.predict(X_test)

In [21]:
# now check the r2 score
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.439933866156897

In [22]:
# our 10 beta values
model.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [23]:
# our b_0 intercept values
model.intercept_

151.88331005254167

## making our own linear regresion

In [24]:
# humna linear regression class banyega fir us par run karega apna data ko aor verify karega
class MeraLR:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)
        
        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
    
    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [25]:
# create a object name our_model 
our_model = MeraLR()

In [26]:
our_model.fit(X_train,y_train)

In [27]:
X_train.shape

(353, 10)

In [28]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

In [29]:
y_pred = our_model.predict(X_test)

In [30]:
r2_score(y_test,y_pred)

0.4399338661568972

In [31]:
# check the coefficinet by our model
our_model.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [32]:
our_model.intercept_

151.88331005254167

observe deko sab kuch same aa raha ha       
that proves ya jo harma code ha aor sklearn library ma jo code dono same ha  matlab sklearn ki linear regression class ma same to same code likha hua ha

tho hamna sctrach sa linear regression sa code ma lika

deko hamna khud sa mathematical formula kiya fir usko python code ma convert kiya is sa bhar aor kuch nahi puch skata 
imagaine aap khud ki library bana raha ho